language: C
compiler: clang
sudo: false

before_install:
  - pip install --user cpp-coveralls

script:
  - make all && make test

after_success:
  - coveralls --exclude tests --exclude obj/tests --gcov-options '\-lp'
